language: ruby
rvm:
- 2.2.2

bundler_args: "--without development"
cache: bundler

before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate

script:
- bundle exec rspec spec

deploy:
  api_key:
    secure: CKGZYEAJ1D+Znzr5XFS/CHA/XndGwAA8b8hWy8sszU9Ey6TFtOOTnJ4qyw4VUChHCw48sdBh/GNa6A5KQtuQ6hOA20MuIn/kdaRkyQyFMhqMkr8JxVXQbzJUHsLGGJusuiqdWUgynNkJZAQElsJncPpksCjK4nBxxhDGqRBFvorfa/yqlYjmMoDJuSngXS8zJksV12euYtmHjvRDzK8J0+JqdjlmLUGksj48DwZeKcVjYwOjVbjs9vTgFFdqnHKNbKclnnZkSzp2OTBH3ew2XWuULjKukQUAsV3UGiE1Eu+xf3rtNtN+/gj+fWUUJ1fZpDFU4/9/Bxtjmgyd3cFFsQgKJKiWNOzAsMp+f9Q1CMhYWPnRZJPnDv6HMPfKVFR+OXXGEjN4wDk1k0dc82Fw8K77zgUwmVbQAuRsdclghIWmRpsYXpP1NM+MDXKTN/X5bPFMJuLN8XdSrF43A6+dPChrcrOV1iQI3jJ7mu9h18vrArEP/RzpUHfCn3yTwjj00RNTlsZf6t/USuAreAE6WdPRTOZCMlJ5FMOUCv6PaxaP+bURWjc1UN188Up6gOmnBHp6HPK40Pqh/yfnYNuArfp2ZieFcYIJrgc6U8uMcruoTgph9oTu25xxQrmogWF+vj3ESiRaYUUnf9o/JujKnQLSEOO/BNqsNVOlX4bD3X8=
